# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest # if failed, try 9.0.2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: |
          echo 'pnpm version:'
          pnpm -v
          pnpm install

      - name: Build static files
        # if failed, ...
        # Treating warnings as errors because process.env.CI = true.
        # Temporarily ignore eslint warnings by setting to false
        run: pnpm run build

      - name: Deploy file to server
        run: |
          zip -9 -r siuka.zip ./apps/suika/build/
          gh release create 0.0.{{ github.run_number }} siuka.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
          
          
